# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anurimoto/Project/Ultra96_Simple/Ultra96_Simple.srcs/sources_1/bd/UART_TEST/ip/UART_TEST_zynq_ultra_ps_e_0_1/UART_TEST_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'UART_TEST_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anurimoto/Project/Ultra96_Simple/Ultra96_Simple.srcs/sources_1/bd/UART_TEST/ip/UART_TEST_zynq_ultra_ps_e_0_1/UART_TEST_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_TEST_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/anurimoto/Project/Ultra96_Simple/Ultra96_Simple.srcs/sources_1/bd/UART_TEST/ip/UART_TEST_zynq_ultra_ps_e_0_1/UART_TEST_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_TEST_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/anurimoto/Project/Ultra96_Simple/Ultra96_Simple.srcs/sources_1/bd/UART_TEST/ip/UART_TEST_zynq_ultra_ps_e_0_1/UART_TEST_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'UART_TEST_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anurimoto/Project/Ultra96_Simple/Ultra96_Simple.srcs/sources_1/bd/UART_TEST/ip/UART_TEST_zynq_ultra_ps_e_0_1/UART_TEST_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_TEST_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/anurimoto/Project/Ultra96_Simple/Ultra96_Simple.srcs/sources_1/bd/UART_TEST/ip/UART_TEST_zynq_ultra_ps_e_0_1/UART_TEST_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_TEST_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
