#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 15 18:17:52 JST 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_Ultra96_behav -key {Behavioral:sim_1:Functional:tb_Ultra96} -tclbatch tb_Ultra96.tcl -protoinst "protoinst_files/UART_TEST.protoinst" -view /home/anurimoto/Project/Ultra96_Simple/tb_Ultra96_behav.wcfg -log simulate.log"
xsim tb_Ultra96_behav -key {Behavioral:sim_1:Functional:tb_Ultra96} -tclbatch tb_Ultra96.tcl -protoinst "protoinst_files/UART_TEST.protoinst" -view /home/anurimoto/Project/Ultra96_Simple/tb_Ultra96_behav.wcfg -log simulate.log

